# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 17:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190102_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
