# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 21:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190102_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AlterField(
            model_name='page',
            name='bodytext',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
