# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190102_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
